### ISSUE TITLE
Internal state were not reset after user's privacy settings reset

### ISSUE THREAD

**Issue by bezigon** [iosphere/ISHPermissionKit#20] opened 2015-01-22 14:08 UTC
Solution?

For microphone I changed code to

```
case AVAudioSessionRecordPermissionUndetermined: {
            ISHPermissionState currentState = [self internalPermissionState];
            if (currentState != ISHPermissionStateAskAgain || currentState != ISHPermissionStateDoNotAskAgain) {
                [self setInternalPermissionState:ISHPermissionStateUnknown];
            }
            return [self internalPermissionState];
        }
```

**Comment by felixLam** [comment] 2015-01-22 14:49
The problem is more generally, that the system does not inform apps about the privacy reset (other than changing the values of particular values, which might also be triggered by individual requests by the user). 

See also my question here:
http://stackoverflow.com/questions/24487660/determine-programmatically-if-the-users-privacy-settings-were-reset

**Comment by felixLam** [comment] 2015-01-22 14:51
So unfortunately I would say that there is very little one can do. We currently do not use the `ISHPermissionStateDoNotAskAgain` option and instead only over: Not now (permission is asked again later), Deny & Allow (both trigger the system dialogue). This allows us to direct the user to the system preferences. If you never ask for permission, the user cannot grant the permissions in settings.

**Comment by felixLam** [comment] 2015-01-22 14:53
We leave the method `changePermissionStateToDontAskFromSender:` in there, in case someone would like to use it and because we believe that users in the "wild" will unlikely reset the entire privacy settings very often. Again we advise not use it. I should maybe make this more clear in the docs.

**Comment by felixLam** [comment] 2015-01-22 14:54
Or did I misunderstand your point?

**Comment by bezigon** [comment] 2015-01-22 15:53
I agree, I don't use these methods. I'm just practicing the possible behaviors of the user.
If in `ISHPermissionKit` alert user agreed, but in native alert refused, and the code took this refusal to the NSUserDefaults.
Next, after the user has reset all settings, he no longer gets `ISHPermissionKit` alerts in the app. From the user's point, he would like to receive alerts again?

**Comment by bezigon** [comment] 2015-01-22 15:59
Indirectly, the reset can be determined by some key constants, for example, for a microphone is `AVAudioSessionRecordPermissionUndetermined`.

**Comment by felixLam** [comment] 2015-01-22 16:08
This needs to be handled on a case by case basis for each permission category. As there is no general way to determine that a reset occurred.

**Comment by felixLam** [comment] 2015-01-22 16:09
I will look over the other categories to see if other changes are required. At least location request seem to have a similar issue in the edge case where whenInUse was granted and always permissions are requested.

**Comment by felixLam** [comment] 2015-01-22 16:10
Meanwhile feel free t look over the linked pull request and check if that fixes your issue. I wanted to avoid resetting the internal state in a getter as this seems to be a bit counter-intuitive.

**Comment by felixLam** [comment] 2015-01-22 16:11
The PR #21 also avoids setting the internal state in the first state on iOS8+ as it is no longer needed.

**Comment by felixLam** [comment] 2015-01-26 08:50
@bezigon Did you have time to test this issue against the linked PR #21?

**Comment by bezigon** [comment] 2015-01-26 13:42
Yes, I tested in particular with a microphone, seems no complaints.

**Comment by felixLam** [comment] 2015-02-18 13:37
#21 has been merged. which should fix this issue.

**Closed** 2015-02-18 13:37 UTC
